### ISSUE TITLE
Change the graphic for the share default link

### ISSUE THREAD

**Issue by cortinico** [gdgpisa/hoverboard#2]
## Expected Behavior
Sharing the link within a social channel should show a fancy GDG Pisa banner.

## Actual Behavior
Sharing the link within a social channel shows a DevFest Ukraine 2016 banner. We must change it.

## Screenshot
<img width="590" alt="screen shot 2017-12-06 at 1 05 08 am" src="https://user-images.githubusercontent.com/3001957/33637519-abafa240-da21-11e7-8dc1-ba03e09e5764.png">

**Comment by domenicoblanco** [comment]
We need to update some meta tags and scrape again the information using the Facebook Debug Tool, I could do it

**Comment by cortinico** [comment]
Actually we just need to update this file here :)
[https://github.com/gdgpisa/hoverboard/blob/master/images/social-share.jpg](https://github.com/gdgpisa/hoverboard/blob/master/images/social-share.jpg)

**Comment by domenicoblanco** [comment]
Do you have something to replace that image?

**Comment by cortinico** [comment]
No we need to do it :/ (ping @dianaberna)

**Comment by domenicoblanco** [comment]
Oh, unluckily I'm not so good with this sort of things :/

**Comment by cortinico** [comment]
Fixed with 44770a05ecdbb082cb2b73ebcb68f764d6f8063c
